# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from solver import Solver
from PyQt6 import QtCore, QtGui, QtWidgets
from auth import AuthApp, launch
import mendeev as me
import rastvr as rs


class MainMenuChemHelper(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(250, 160, 311, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Mendeleev = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Mendeleev.setObjectName("Mendeleev")
        self.gridLayout.addWidget(self.Mendeleev, 2, 0, 1, 1)
        self.Zadachi = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.Zadachi.setObjectName("Zadachi")
        self.gridLayout.addWidget(self.Zadachi, 0, 0, 1, 1)
        self.tablitsyaRastv = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.tablitsyaRastv.setObjectName("tablitsyaRastv")
        self.gridLayout.addWidget(self.tablitsyaRastv, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 50, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 470, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Mendeleev.setText(_translate("MainWindow", "Таблица Менделеева"))
        self.Zadachi.setText(_translate("MainWindow", "Решить задачу по Химии"))
        self.tablitsyaRastv.setText(_translate("MainWindow", "Таблица Растворимостей"))
        self.label.setText(_translate("MainWindow", "ChemistryLab Dev"))
        self.pushButton.setText(_translate("MainWindow", "Профиль"))
        self.pushButton.clicked.connect(self.open_login_window)
        self.Mendeleev.clicked.connect(self.open_mendelev)
        self.tablitsyaRastv.clicked.connect(self.open_rastr)
        self.Zadachi.clicked.connect(self.open_login_window)

    def open_login_window(self):
        print("открытие профиля")
        try:
            window = AuthApp()
            window.show()
        except Exception as e:
            print(f"Ошибка при открытии окна логина: {e}")
    def open_mendelev(self):
        print("открытие таблицы")
        try:
            profile_window = me.tab()
            profile_window.show()
        except Exception as e:
            print(f"Ошибка при открытии окна таблицы: {e}")
    def open_rastr(self):
        print("открытие таблицы")
        try:
            profile_window = rs.tab()
            profile_window.show()
        except Exception as e:
            print(f"Ошибка при открытии окна таблицы: {e}")
    def open_solver(self):
        print("открытие окна")
        try:
            profile_window = Solver()
            profile_window.show()
        except Exception as e:
            print(f"Ошибка при открытии окна: {e}")
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainMenuChemHelper()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
